# Generated by Django 5.0.6 on 2024-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
