version: '3.9'

services:
  web:
    restart: always
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/app/.env
