global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/prometheus-xyzabc/metrics'
    static_configs:
      - targets: ['0.0.0.0:8080']